spring.datasource.url=jdbc:postgresql://localhost:5432/simple_auth_db
spring.datasource.username=postgres
spring.datasource.password=2506Aa#*

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect